Fix some bugs and add new commands to GUI

diff --git a/initrepo b/initrepo
--- a/initrepo
+++ b/initrepo
@@ -9,7 +9,7 @@ function readdefault {
 }
 
 # Sanity checks
-[ -z $(which git-flow) ] && echo "Can't find git-flow. Please install." && exit 1
+[ -z "$(which git-flow)" ] && echo "Can't find git-flow. Please install." && exit 1
 
 gerritusername=$(git config --get fwinit.gerrituser)
 username=$(git config --get user.name)
@@ -20,27 +20,27 @@ mergetool=${mergetool:-p4merge}
 savevalues=false
 
 # Query user for variables
-if [ -z $username ]; then
-	username=$(readdefault "Full name" ${username:-$(whoami)})
+if [ -z "$username" ]; then
+	username=$(readdefault "Full name" "${username:-$(whoami)}")
 	savevalues=true
 fi
-if [ -z $useremail ]; then
+if [ -z "$useremail" ]; then
 	tmpemail="${username// /_}@sil.org"
-	useremail=${useremail:-$tmpemail}
-	useremail=$(readdefault "Email" $useremail)
+	useremail="${useremail:-$tmpemail}"
+	useremail=$(readdefault "Email" "$useremail")
 	savevalues=true
 fi
-if [ -z $gerritusername ]; then
-	gerritusername=${gerritusername:-$username}
-	gerritusername=$(readdefault "Gerrit username" ${gerritusername:-$(whoami)})
+if [ -z "$gerritusername" ]; then
+	gerritusername="${gerritusername:-$username}"
+	gerritusername=$(readdefault "Gerrit username" "${gerritusername:-$(whoami)}")
 	savevalues=true
 fi
 
 if $savevalues; then
 	# Store variables for later use
-	git config --global user.name $username
-	git config --global user.email $useremail
-	git config --global fwinit.gerrituser $gerritusername
+	git config --global user.name "$username"
+	git config --global user.email "$useremail"
+	git config --global fwinit.gerrituser "$gerritusername"
 fi
 
 if [ -d .git ]; then
@@ -130,6 +130,8 @@ git config guitool.Release/Start.cmd 'git flow release start $ARGS'
 git config guitool.Release/Start.argprompt yes
 git config guitool.Release/Review.cmd 'git push review HEAD:refs/for/$CUR_BRANCH'
 git config guitool.Release/Finish.cmd 'git flow release finish ${CUR_BRANCH#*/} && git pull review develop && git push review --all && git push review --tags :refs/heads/$CUR_BRANCH'
+git config guitool.Release/Track.cmd 'git flow release track $ARGS'
+git config guitool.Release/Track.argprompt yes
 
 git config guitool.Hotfix/Start.cmd 'git flow hotfix start $ARGS'
 git config guitool.Hotfix/Start.argprompt yes
@@ -148,4 +150,6 @@ git config "guitool.Interactive Rebase.revprompt" yes
 git config "guitool.Visual Diff.cmd" 'git difftool -y $FILENAME'
 git config "guitool.Visual Diff.needsfile" yes
 git config "guitool.Visual Diff.noconsole" yes
+git config "guitool.Visual Merge.cmd" 'git mergetool -y'
+git config "guitool.Visual Merge.noconsole" yes
 
