Use a better test for the presence of git-flow
git-flow is now a package, but this doesn't put a git-flow executable
anywhere on the PATH

diff --git a/fwmeta/initrepo b/fwmeta/initrepo
--- a/fwmeta/initrepo
+++ b/fwmeta/initrepo
@@ -161,7 +161,10 @@ reset=0
 cd $basedir
 
 # Sanity checks
-[ -z "$(which git-flow)" ] && echo "Can't find git-flow. Please install." && exit 1
+if ! git flow version &>/dev/null; then
+	echo "Can't find git-flow. Please install."
+	exit 1
+fi
 
 gerritusername=$(git config --get fwinit.gerrituser)
 username=$(git config --get user.name)
