Add ability to create topic branches on release branches
This change allows creating a feature branch based on
release and hotfix branches.

It also allows creating a topic branch based on a long-lived
feature branch.

Change-Id: I79784d64821f497942cb5fff2d86a265a7c8ac7b

diff --git a/fwmeta/initrepo b/fwmeta/initrepo
--- a/fwmeta/initrepo
+++ b/fwmeta/initrepo
@@ -11,7 +11,7 @@ TOOLSDIR=fwmeta
 # Version of the alias section in the config file. Increment the number each time you make some
 # changes to setting the alias/guitool section below so that the config gets updated when this
 # script is run.
-THISALIASVERSION=10
+THISALIASVERSION=11
 
 # Display help
 help()
@@ -314,6 +314,12 @@ initrepo()
 			git config --remove-section "guitool.Interactive Rebase (Abort)" 2> /dev/null || true
 			git config --remove-section guitool.Rebase 2> /dev/null || true
 		fi
+		if [ "$(git config --get fwinit.aliasversion || echo -1)" -lt "11" -o "$reset" = "1" ]; then
+			# More cleanup
+			git config --remove-section "guitool.1_Release/0_Start" 2> /dev/null || true
+			git config --remove-section "guitool.2_Hotfix/0_Start" 2> /dev/null || true
+			git config --remove-section "guitool.3_Support/0_Start" 2> /dev/null || true
+		fi
 
 		sedReplace="$basedir/$TOOLSDIR"
 		sedReplace=${sedReplace//\//\\\/} # replace all / with \/
@@ -327,11 +333,12 @@ initrepo()
 		git config alias.globstat '!sh -c "SEDREPLACE/repostatus \$1" -'
 		git config alias.bypass '!sh -c "SEDREPLACE/bypass.sh" -'
 		git config alias.track '!sh -c "SEDREPLACE/git-track \$1" -'
+		git config alias.start '!sh -c "SEDREPLACE/git-start-task \$@" -'
 		# do this last so that we can replace multiple entries at once
 		sed "s/SEDREPLACE/$sedReplace/g" .git/config 2>&1 > .git/config2
 		mv .git/config2 .git/config
 
-		git config guitool.0_Feature/0_Start.cmd 'git flow feature start $ARGS'
+		git config guitool.0_Feature/0_Start.cmd 'git start develop $ARGS'
 		git config guitool.0_Feature/0_Start.argprompt "Feature name (JIRA number)"
 		git config "guitool.0_Feature/1_Submit for Code Review.cmd" 'git push origin HEAD:refs/for/develop/$CUR_BRANCH'
 		git config guitool.0_Feature/2_Finish.cmd 'GIT_EDITOR=$(git config --get gui.editor) git featfin ${CUR_BRANCH#*/}'
@@ -339,23 +346,23 @@ initrepo()
 		git config guitool.0_Feature/Track.cmd 'git track feature/$ARGS'
 		git config guitool.0_Feature/Track.argprompt "Name of the feature (without feature/ prefix)"
 
-		git config guitool.1_Release/0_Start.cmd 'git flow release start $ARGS'
-		git config guitool.1_Release/0_Start.argprompt "Name of the release"
+		git config "guitool.1_Release/0_Start Bugfix.cmd" 'git start release $ARGS'
+		git config "guitool.1_Release/0_Start Bugfix.argprompt" "Bugfix name (JIRA number)"
 		git config "guitool.1_Release/1_Submit for Code Review.cmd" 'git push origin HEAD:refs/for/$CUR_BRANCH'
 		git config guitool.1_Release/2_Finish.cmd 'GIT_EDITOR=$(git config --get gui.editor) git release ${CUR_BRANCH#*/}'
 		git config guitool.1_Release/Publish.cmd 'git flow release publish ${CUR_BRANCH#*/}'
 		git config guitool.1_Release/Track.cmd 'git track release/$ARGS'
 		git config guitool.1_Release/Track.argprompt "Name of the release (without release/ prefix)"
 
-		git config guitool.2_Hotfix/0_Start.cmd 'git flow hotfix start $ARGS'
-		git config guitool.2_Hotfix/0_Start.argprompt "Name of the fixed version"
+		git config "guitool.2_Hotfix/0_Start Bugfix.cmd" 'git start hotfix $ARGS'
+		git config "guitool.2_Hotfix/0_Start Bugfix.argprompt" "Bugfix name (JIRA number)"
 		git config "guitool.2_Hotfix/1_Submit for Code Review.cmd" 'git push origin HEAD:refs/for/$CUR_BRANCH'
 		git config guitool.2_Hotfix/2_Finish.cmd 'GIT_EDITOR=$(git config --get gui.editor) git hotfin ${CUR_BRANCH#*/}'
 		git config guitool.2_Hotfix/Track.cmd 'git track hotfix/$ARGS'
 		git config guitool.2_Hotfix/Track.argprompt "Name of the hotfix (without hotfix/ prefix)"
 
-		git config guitool.3_Support/0_Start.cmd 'git flow support start $ARGS'
-		git config guitool.3_Support/0_Start.argprompt "Name of the support branch and tag it is based on (e.g. '1.0 1.0')"
+		git config "guitool.3_Support/0_Start Bugfix.cmd" 'git start support $ARGS $CUR_BRANCH'
+		git config "guitool.3_Support/0_Start Bugfix.argprompt" "Bugfix name (JIRA number)"
 		git config "guitool.3_Support/1_Submit for Code Review.cmd" 'git push origin HEAD:refs/for/$CUR_BRANCH'
 		git config guitool.3_Support/2_Finish.cmd 'GIT_EDITOR=$(git config --get gui.editor) git supfin $ARGS'
 		git config guitool.3_Support/2_Finish.argprompt "Name of the new version"
