Improve argument processing
Also implement --help option. Also included is a getopt.exe binary
that implements getopt(1) on Windows. The getopt version included
for git-flow has problems with long options.

getopt.exe was compiled with VS2010 on Windows with the sources from
tag 1.1.4-1
(https://github.com/ermshiperete/getopt/commit/d1c2932133).

Change-Id: I7c7ae1db51a8691c6b023e427e130dd55f12cce6

diff --git a/fwmeta/initrepo b/fwmeta/initrepo
--- a/fwmeta/initrepo
+++ b/fwmeta/initrepo
@@ -19,6 +19,22 @@ TOOLSDIR=fwmeta
 # script is run.
 THISALIASVERSION=8
 
+# Display help
+help()
+{
+echo -e "Usage:\
+\n    $(basename "$0") [options]
+
+Options:\
+\n    --reset    Reset repo by asking all questions and performing all\
+\n               initializations again.\
+\n    --modify   Allow changing the selection of repos and branches.\
+\n               Note: this doesn't delete any repos or branches.\
+\n    -h|--help  Display this help screen.\
+\n    --debug    Output debug information.\
+\n"
+}
+
 # Get the directory of the fwmeta repo. We can't do that in functions.sh because we need to
 # know the directory before we can include functions.sh!
 getfwmetadirBootStrap()
@@ -281,21 +297,44 @@ initrepo()
 	cd "$cwd"
 }
 
-if echo "$*" | grep "\--debug" > /dev/null; then
-	DEBUG=1
+
+basedir="$(getfwmetadirBootStrap)"
+# On Windows we want to use getopt in our directory since the other one
+# is broken
+if [ "$OSTYPE" = "msys" ]; then
+	GETOPT="$basedir/$TOOLSDIR/getopt"
+else
+	GETOPT="getopt"
 fi
 
-[ $DEBUG ] && echo "ARGS=$*"
+ORIG_ARGS=("$@")
+OPTS=$($GETOPT -o h --long help --long debug --long recursive --long reset --long modify -n "$(basename "$0")" -- "$@")
+
+eval set -- "$OPTS"
+
+while true ; do
+	case "$1" in
+		-h|--help) help ; exit 0;;
+		--debug) DEBUG=1 ;;
+		--recursive) RECURSIVE=1 ;;
+		--reset) reset=1 ;;
+		--modify) modify=1 ;;
+		--) shift; break;;
+		*) echo "Internal error: Unknown argument $1!" ; exit 1 ;;
+	esac
+	shift
+done
+
+[ $DEBUG ] && echo -e "***************\nARGS=${ORIG_ARGS[@]}"
 
 defaultbranches="master develop"
 if [ "$OSTYPE" = "linux-gnu" ]; then
 	defaultbranches+=" support/7.0-Linux"
 fi
 
-basedir="$(getfwmetadirBootStrap)"
 [ $DEBUG ] && echo "basedir=$basedir"
 cd "$basedir"
-if ! echo "$*" | grep "\--recursive" > /dev/null; then
+if [ ! $RECURSIVE ]; then
 	branchlist="$defaultbranches"
 	[ $DEBUG ] && echo "Called non-recursive"
 	if [ -d ".git" ] && git remote | grep -q origin ; then
@@ -316,14 +355,9 @@ if ! echo "$*" | grep "\--recursive" > /dev/null; then
 	fi
 	echo
 	# recursive call so that we run with the latest version
-	exec "$basedir/$TOOLSDIR/initrepo" --recursive "$@"
+	exec "$basedir/$TOOLSDIR/initrepo" --recursive "${ORIG_ARGS[@]}"
 fi
-shift
 [ $DEBUG ] && echo "Called recursively"
-reset=0
-[ "$1" = "--reset" ] && reset=1
-modify=0
-[ "$1" = "--modify" ] && modify=1
 
 . "$basedir/$TOOLSDIR/functions.sh"
 . "$basedir/$TOOLSDIR/repodefs.sh"
