Verify entered repo names
Compare the repo names that the user entered with the
list of available repos. If the user entered a non-existing
name he can enter it again. This makes it more obvious what
the problem is.

Change-Id: I23da0e79bb1c4381fb2deb03cd48ffe00c0f9c19

diff --git a/fwmeta/initrepo b/fwmeta/initrepo
--- a/fwmeta/initrepo
+++ b/fwmeta/initrepo
@@ -356,13 +356,24 @@ fi
 repolist=$(git config --get fwinit.repolist) || true
 [ "$reset" = 1 ] && repolist=""
 if [ -z "$repolist" ]; then
-	echo "Available repos: $(getAllReposForPlatform)"
-	defaultlist="FieldWorks FwSampleProjects"
-	if [ "$(platform)" = "Linux" ]; then
-		defaultlist+=" mono mono-basic gtk-sharp libgdiplus"
-	fi
+	while [ -z "$repolist" ]
+	do
+		echo "Available repos: $(getAllReposForPlatform)"
+		defaultlist="FieldWorks FwSampleProjects"
+		if [ "$(platform)" = "Linux" ]; then
+			defaultlist+=" mono mono-basic gtk-sharp libgdiplus"
+		fi
+		repolist=$(readdefault "Repos to clone" "$defaultlist")
+		for repo in $repolist; do
+			if ! echo "$(getAllReposForPlatform)" | grep -E "(^| )$repo( |$)" >& /dev/null; then
+				echo
+				printf "${_bold}Can't find \"%q\". Please try again.${_normal}\n" $repo
+				repolist=""
+				break
+			fi
+		done
+	done;
 
-	repolist=$(readdefault "Repos to clone" "$defaultlist")
 	git config fwinit.repolist "$repolist"
 fi
 branchlist=$(git config --get fwinit.branchlist) || true
